### PR TITLE
fix: upload video erros

### PR DESCRIPTION
**Pull request by bikekoala**

### CODE REVIEW

**Comment by egeldenhuys** [comment]
Hi @bikekoala , thank you for the pull request!
I have not tried uploading videos yet so I did not know about the error.

I will test it in the next week and merge if everything works fine.

**Comment by fritz-fritz** [comment]
Hmm, I can verify that this does indeed allow the upload to complete and be served... but it seems we might be missing something in the storage api as it leads to a thumbnail being generated and stored at `/undefined/<media name>_thumb.jpg`

This might be a temporarily okay bit to merge. But I think more work is needed.

**Comment by egeldenhuys** [comment]
Thank you for the feedback @fritz-fritz !

I created an issue for the thumbnail storage bug.

**Comment by fritz-fritz** [comment]
Hmm, when I tested. I manually applied the change in the `src/index.ts` but didn't switch to the branch so didn't have the changes in the `package-lock.json`. They seem to be breaking my uploads somehow. You might need to rollback if you haven't tested?

**Pull request merged**
